services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"

      PRODUCTS_JSON_PATH: "${PRODUCTS_JSON_PATH:-/app/src/entrypoints/mcp_products_server/data/products.json}"
      MCP_PRODUCTS_SERVER_PATH: "${MCP_PRODUCTS_SERVER_PATH:-/app/src/entrypoints/mcp_products_server/server.py}"

      ORDERS_JSON_PATH: "${ORDERS_JSON_PATH:-/app/src/entrypoints/mcp_orders_server/data/orders.json}"
      MCP_ORDERS_SERVER_PATH: "${MCP_ORDERS_SERVER_PATH:-/app/src/entrypoints/mcp_orders_server/server.py}"
